# -*- coding: utf-8 -*-
"""04Function-AzrielAldrinSenandoSiahaan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1ifDF-t6TtR8aCaOmfo4VTyIpmZMv1Z

<h1>Fungsi dalam Python</h1>

<p> <strong> Selamat datang! </strong> Modul ini akan mengajarkan Anda tentang fungsi-fungsi dalam bahasa pemrograman Python. Di akhir modul ini, Anda akan mengetahui konsep dasar tentang fungsi, variabel, dan cara menggunakan fungsi. </p>

**Petunjuk pengerjaan:**

1.   Buatlah salinan project ini dengan memilih menu File - Save a Copy in Drive.
2.   Gantilah nama filenya dengan **04Function-(NamaLengkap).ipynb**

**Petunjuk pengumpulan:**

1.   Bagikanlah project kalian pada saya, dengan menekan tombol Share (Bagikan)  di kanan atas.
2.   Pilih "***Anyone with the link***"
1.   Salin linknya, lalu
1.   Kumpulkan di bagian tugas yang bersesuaian di platform yang digunakan di kelas.

Lalu baca dan ikutilah petunjuk selanjutnya dari modul ini.

<h2> Daftar Isi </h2>
<div class = "alert alert-block alert-info" style = "margin-top: 20px">
     <ul>
         <li>
             <a href="#func"> Fungsi </a>
             <ul>
                 <li> <a href="content"> Apa itu fungsi? </a> </li>
                 <li> <a href="var"> Variabel </a> </li>
                 <li> <a href="simple"> Fungsi Membuat Segalanya Sederhana </a> </li>
             </ul>
         </li>
         <li> <a href="pre">Pre-defined Function </a> </li>
         <li> <a href="if"> Branching dan Looping dalam Fungsi </a> </li>
         <li> <a href="default"> Setting Nilai Argumen Default dalam Fungsi Custom</a> </li>
         <li> <a href="global"> Variabel global </a> </li>
         <li> <a href="scope"> Cakupan Variabel </a> </li>
         <li> <a href="collec"> Koleksi dan Fungsi </a> </li>
         <li>
             <a href="#quiz"> Kuis tentang Fungsi </a>
         </li>
     </ul>

</div>

<hr>

<h2 id="func">Fungsi</h2>

Fungsi adalah blok kode yang melakukan operasi tertentu dan dapat digunakan kembali. Fungsi memecah tugas besar ke dalam bagian-bagian yang lebih kecil dan memungkinkan Anda untuk menggunakan kembali fungsi dalam program yang berbeda.

Ada dua jenis fungsi:

- <b> Pre-defined Functions</b>
- <b> User Defined Functions</b>

<h3 id = "content"> Apa itu Fungsi? </h3>

Anda dapat membuat fungsi untuk menyediakan fungsi tertentu yang diperlukan. Berikut adalah aturan sederhana untuk mendefinisikan sebuah fungsi dalam Python:

- Blok fungsi dimulai dengan <code>def</code> diikuti oleh <code> nama</code> fungsi dan tanda kurung <code>()</code>.
- Di dalam tanda kurung ini, Anda dapat menentukan parameter sebagai input (masukan data) ke fungsi.
- Sebelum masuk ke isi fungsi, ada tanda titik dua (<code>:</code>) dan di baris selanjutnya adalah isi dari fungsi yang dinyatakan dengan instruksi-instruksi yang diberi indentasi.
- Anda juga dapat menambahkan komentar dokumentasi di dalam fungsi.
- Jika fungsi perlu mengembalikan nilai, maka gunakan statement <code>return</code> sebelum keluar dari fungsi.

Contoh dari fungsi dengan sebuah parameter <code> a </code> dapat dilihat pada contoh berikut. Fungsi ini mencetak dan mengembalikan nilai <code>b</code> sebagai keluaran fungsi.
"""

# Fungsi add: menerima sebuah parameter a, kemudiannya menyimpan nilai a+1 di variabel b yang merupakan nilai kembalian dari fungsi

def add(a):
    b = a + 1
    print(a, "if you add one", b)
    return(b)

"""Gambar berikut mengilustrasikan cara mendeklarasikan fungsi:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/FuncsDefinition.png" width="500" />

Kami dapat memperoleh informasi tentang suatu fungsi:
"""

# Mendapatkan informasi fungsi add:

help(add)

"""Cara memanggil fungsi adalah dengan menyebut nama fungsi dan argumen (nilai yang dikirim ke parameter) sesuai definisi fungsi."""

# Memanggil fungsi add()

add(1)

"""Jika kita memanggil fungsi dengan nilai argumen baru, kita akan mendapatkan hasil baru:"""

# Pemanggilan lain fungsi add()

add(2)

"""Mari kita buat fungsi lain. Misalnya, kita buat fungsi yang mengalikan dua angka. Angka-angka tersebut akan diwakili oleh variabel <code> a</code> dan <code> b</code>:"""

# Definisi fungsi untuk mengalikan dua nilai: a dan b

def mult(a, b):
    c = a * b
    return(c)
    print('This is not printed')

result = mult(12,2)
print(result)

"""Fungsi yang sama dapat digunakan untuk tipe data berbeda. Misalnya, kita bisa mengalikan dua bilangan bulat:"""

# Memanggil fungsi mult() untuk mengalikan dua bilangan bulat

mult(2, 3)

"""Perhatikan bagaimana fungsi berhenti pada pernyataan <code> return</code>, sambil mengembalikan sebuah nilai. Nilai ini selanjutnya dapat disimpan dalam variabel lain sesuai kebutuhan.

<hr>
Fungsi yang sama dapat digunakan untuk tipe data yang berbeda. Misalnya, kita bisa mengalikan dua bilangan desimal:
"""

# Memanggil fungsi mult() untuk mengalikan dua bilangan desimal (floats)

mult(10.0, 3.14)

"""Kita bahkan bisa mereplikasi string dengan mengalikannya dengan bilangan bulat:"""

# Memanggil fungsi mult() untuk mengalikan dua tipe berbeda: integer dan string

mult(2, "Michael Jackson ")

"""<h3 id="var">Variabel</h3>

Data masukan ke suatu fungsi disebut parameter.

Variabel yang dideklarasikan di dalam fungsi disebut **variabel lokal**. Parameter fungsi termasuk ke dalam variabel lokal karena parameter hanya "dikenal" di dalam fungsi. Di luar fungsi, variabel lokal tidak terdefinisi (tidak "dikenal" atau tidak dapat digunakan).

Variabel yang dideklarasikan di luar definisi fungsi disebut **variabel global**, dan nilainya dapat diakses dan dimodifikasi di seluruh program. Kita akan membahas lebih lanjut tentang variabel global di akhir modul.
"""

# Definisi fungsi

def square(a):

    # variable local: a, b, c
    b = 1
    c = a * a + b
    print(a, "if you square + 1", c)
    return(c)

"""Label gambar berikut menjelaskan bagian-bagian tersebut:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/FuncsVar.png" width="500" />

Kita dapat memanggil fungsi dengan input <b> 3 </b>:
"""

# Inisialisasi variabel global

x = 3
# Membuat pemanggilan fungsi square. Nilai kembalian fungsi disimpan dalam variabel y
y = square(x)
y

"""Kita dapat memanggil fungsi dengan masukan nilai <b>2</b> dengan cara yang berbeda:"""

# Mengirimkan angka 2 sebagai parameter secara langsung

square(2)

"""Jika tidak ada *statement* <code> return</code>, fungsi tersebut mengembalikan <code> None</code>. Dua fungsi berikut ini menunjukkan fungsi yang sama:"""

# Dua definisi fungsi yang sama: satu fungsi dengan return value None dan fungsi lain tanpa return value

def MJ():
    print('Michael Jackson')

def MJ1():
    print('Michael Jackson')
    return(None)

# Lihat outputnya

MJ()

# Lihat outputnya

MJ1()

"""Secara default, fungsi mengembalikan **None** setelah pemanggilan fungsi."""

# Lihat return fungsi

print(MJ())
print(MJ1())

"""Buat fungsi <code>con</code> yang menggabungkan dua string menggunakan operasi penambahan:"""

# Deklarasi fungsi untuk menggabungkan dua string

def con(a, b):
    return(a + b)

# Memanggil fungsi con()

con("This ", "is")

"""<jam />
     <div class = "alert alert-success alertsuccess" style = "margin-top: 20px">
         <h4> [Tip] Bagaimana cara mempelajari lebih lanjut tentang pre-defined function dalam Python? </h4>
         <p> Ada terlalu banyak pre-defined function, jadi tidak mungkin bisa diajarkan semuanya dalam satu kesempatan. Namun jika Anda ingin melihat sekilas, berikut adalah referensi singkat untuk beberapa pre-defined function yang umum digunakan: <a href = "https://drive.google.com/file/d/1_E872o_AEFEBftLgXZsXwdCL-bl-qAnw/view?usp=sharing">Referensi </a> </p>
     </div>
<jam />

<h3 id = "simple"> Fungsi Membuat Segalanya Sederhana </h3>

Perhatikan dua blok kode berikut ini: <b> Blok 1 </b> dan <b> Blok 2 </b>. Prosedur untuk setiap blok identik. Satu-satunya hal yang berbeda adalah nama dan nilai variabel.

<h4>Block 1:</h4>
"""

# a dan b - perhitungan block1

a1 = 4
b1 = 5
c1 = a1 + b1 + 2 * a1 * b1 - 1
if(c1 < 0):
    c1 = 0
else:
    c1 = 5
c1

"""<h4>Block 2:</h4>

"""

# a dan b - perhitungan block2

a2 = 0
b2 = 0
c2 = a2 + b2 + 2 * a2 * b2 - 1
if(c2 < 0):
    c2 = 0
else:
    c2 = 5
c2

"""Kita dapat mengganti block kode tersebut dengan fungsi. Sebuah fungsi menggabungkan banyak instruksi menjadi satu baris kode. Setelah fungsi dideklarasikan, fungsi dapat digunakan berulang kali. Anda dapat menjalankan fungsi yang sama berkali-kali dalam program Anda. Anda dapat menyimpan fungsi Anda dan menggunakannya di program lain atau menggunakan fungsi orang lain. Baris kode pada kode <b> Block 1 </b> dan kode <b> Block 2 </b> dapat diganti dengan fungsi sebagai berikut:"""

# membuat fungsi untuk menggantikan kedua block program di atas

def Equation(a,b):
    c = a + b + 2 * a * b - 1
    if(c < 0):
        c = 0
    else:
        c = 5
    return(c)

"""Fungsi ini menerima dua masukan, a dan b, kemudian menerapkan beberapa operasi kemudian mengembalikan nilai c.
Kita cukup mendefinisikan fungsi satu kali (mengganti block instruksi yang sama dengan fungsi) dan memasukkan nilai berbeda pada setiap pemanggilan berbeda:
* Pemanggilan pertama dengan nilai argumen <code> a1 </code>, <code> b1 </code> dan
* Pemanggilan kedua dengan nilai argumen <code> a2 </code>, <code> b2 </code> sebagai masukan.

Keseluruh proses diilustrasikan pada gambar:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/FuncsPros.gif" width="850" />

Kode **Blok 1** dan **Blok 2** kini dapat diganti dengan kode **Blok 3** dan kode **Blok 4**.

<h4>Block 3:</h4>
"""

a1 = 4
b1 = 5
c1 = Equation(a1, b1)
c1

"""<h4>Block 4:</h4>

"""

a2 = 0
b2 = 0
c2 = Equation(a2, b2)
c2

"""<hr>

<h2 id="pre">Pre-defined Functions</h2>

Ada banyak pre-defined functions dalam Python. Mari kita pelajari dari yang paling sederhana!

Fungsi <code>print()</code>:
"""

# Build-in function print()

album_ratings = [10.0, 8.5, 9.5, 7.0, 7.0, 9.5, 9.0, 9.5]
print(album_ratings)

"""Fungsi <code>sum()</code> menambahkan semua element dalam list atau tuple:

"""

# Menggunakan pre-defined function sum() untuk menambahkan semua elemen dalam list atau tuple

sum(album_ratings)

"""Fungsi <code>len()</code> mengembalikan panjang (banyaknya elemen) dari sebuah list atau tuple:

"""

# Mengembalikan panjang list atau tuple

len(album_ratings)

"""<h2 id = "if">Branching dan Looping dalam Fungsi </h2>

Fungsi <code>return()</code> sangat berguna jika Anda memiliki pernyataan IF dalam fungsi tersebut, saat Anda ingin keluaran fungsi Anda bergantung pada beberapa kondisi:
"""

# Contoh fungsi

def type_of_album(artist, album, year_released):

    print(artist, album, year_released)
    if year_released > 1980:
        return "Modern"
    else:
        return "Oldie"

x = type_of_album("Michael Jackson", "Thriller", 1980)
print(x)

"""Kita dapat menggunakan loop dalam suatu fungsi. Misalnya, kita gunakan *loop* untuk <code> mencetak </code> setiap elemen dalam list:"""

# Fungsi untuk mencetak seluruh elemen list menggunakan for loop

def printList(the_list):
    for element in the_list:
        print(element)

# memanggil fungsi printList

printList(['1', 1, 'the man', "abc"])

"""<hr>

<h2 id="default">Setting Nilai Argumen Default dalam User-Defined Function </h2>

Anda dapat men-set nilai default untuk argumen dalam fungsi Anda.

Misal, dalam fungsi <code> isGoodRating()</code> di bawah, kita ingin membuat batas untuk apa yang kita anggap sebagai peringkat yang baik. Secara default, kita set nilai peringkat dengan nilai 4.
"""

# Contoh setting parameter dengan nilai default

def isGoodRating(rating=4):
    if(rating < 7):
        print("This album sucks, it's rating is ",rating)

    else:
        print("This album is good, its rating is",rating)

# Menguji dengan nilai default value dan dengan nilai input

isGoodRating()
isGoodRating(10)

"""<hr>

<h2 id="global">Global variables</h2>

Sejauh ini, kita telah membuat variabel di dalam fungsi, tetapi kami belum membahas variabel di luar fungsi. Variabel di luar fungsi disebut **variabel global**.
<br>

Mari kita lihat apa yang dihasilkan fungsi <code> printer1 </code>:
"""

# Contoh variabel global

artist = "Michael Jackson"
def printer1(artist):
    internal_var1 = artist
    print(artist, "is an artist")

printer1(artist)
# coba jalankan kode berikut ini
#printer1(internal_var1)

"""<b> Kita mendapat pesan kesalahan: <code>name 'internal_var' is not defined</code>. Mengapa? </b>

Itu karena semua variabel yang kita buat di dalam fungsi adalah <b> variabel lokal </b>, artinya variabel tidak dapat diakses di luar fungsi.

Tetapi ada cara untuk membuat <b> variabel global </b> dari dalam fungsi. Caranya adalah dengan menggunakan *keyword* **global**:
"""

artist = "Michael Jackson"

def printer(artist):
    global internal_var
    internal_var= "Whitney Houston"
    print(artist,"is an artist")

printer(artist)
printer(internal_var)

"""<h2 id="scope">Cakupan (Scope) Variabel</h2>

Cakupan variabel adalah bagian dari program di mana variabel itu dapat diakses. Variabel yang dideklarasikan di luar definisi fungsi, seperti variabel <code> myFavouriteBand</code> dalam kode di bawah, dapat diakses dari mana saja dalam program. Akibatnya, variabel-variabel tersebut dikatakan memiliki cakupan global, dan disebut sebagai **variabel global**.
*     <code> myFavouriteBand </code> adalah variabel global, jadi bisa diakses dari dalam fungsi <code> getBandRating </code>, dan kita bisa menggunakannya untuk menentukan peringkat sebuah band. Kita juga bisa menggunakannya di luar fungsi, seperti saat kita meneruskannya ke fungsi print untuk menampilkannya:
"""

# Contoh variabel  global

myFavouriteBand = "AC/DC"

def getBandRating(bandname):
    if bandname == myFavouriteBand:
        return 10.0
    else:
        return 0.0

print("AC/DC's rating is:", getBandRating("AC/DC"))
print("Deep Purple's rating is:",getBandRating("Deep Purple"))
print("My favourite band is:", myFavouriteBand)

"""Lihatlah versi kode yang dimodifikasi berikut ini.
* Sekarang variabel <code> myFavouriteBand</code> didefinisikan dalam fungsi <code> getBandRating</code>. Variabel yang didefinisikan dalam suatu fungsi disebut sebagai **variabel lokal** dari fungsi tersebut. Hal ini berarti bahwa variabel tersebut hanya dapat diakses dari dalam fungsi yang didefinisikan
* Fungsi <code> getBandRating</code> akan tetap berfungsi, karena <code> myFavouriteBand </code> masih ditentukan di dalam fungsi tersebut. Namun, kita tidak bisa lagi mencetak <code> myFavouriteBand</code> di luar fungsi, karena variabel <code> myFavouriteBand</code> adalah variabel lokal dari fungsi <code> getBandRating </code>:
"""

# Contoh variabel lokal

def getBandRating(bandname):
    myFavouriteBand = "AC/DC"
    if bandname == myFavouriteBand:
        return 10.0
    else:
        return 0.0

print("AC/DC's rating is: ", getBandRating("AC/DC"))
print("Deep Purple's rating is: ", getBandRating("Deep Purple"))
print("My favourite band is", myFavouriteBand)

"""Terakhir, lihat contoh berikut ini.

Kita sekarang memiliki dua definisi variabel <code> myFavouriteBand</code>:
* Yang pertama memiliki cakupan global, dan
* yang kedua adalah variabel lokal dalam fungsi <code> getBandRating </code>.

Dalam fungsi <code> getBandRating</code>, variabel lokal diutamakan. **Deep Purple** akan menerima peringkat 10.0 saat dikirim ke fungsi <code>getBandRating</code>. Namun, di luar fungsi <code> getBandRating</code>, variabel lokal <code> getBandRating</code> tidak terdefinisi, jadi variabel <code> myFavouriteBand</code> yang kita cetak adalah variabel global, yang memiliki nilai **AC/DC**:
"""

# Contoh variabel global dan variabel local dengan nama yang sama

myFavouriteBand = "AC/DC"

def getBandRating(bandname):
    myFavouriteBand = "Deep Purple"
    if bandname == myFavouriteBand:
        return 10.0
    else:
        return 0.0

print("AC/DC's rating is:",getBandRating("AC/DC"))
print("Deep Purple's rating is: ",getBandRating("Deep Purple"))
print("My favourite band is:",myFavouriteBand)

"""<hr>
<h2 id ="collec"> Koleksi dan Fungsi</h2>

Ketika jumlah argumen tidak diketahui untuk suatu fungsi, semua argumen dapat dikemas dalam tupel seperti yang ditunjukkan pada contoh berikut ini:
"""

def printAll(*args): # Semua arguments dibungkus dalam args yang dapat diperlakukan seperti sebuah tuple
    print("No of arguments:", len(args))
    for argument in args:
        print(argument)

#printAll dengan 3 argumen
printAll('Horsefeather','Adonis','Bone')

#printAll dengan 4 argumen
printAll('Sidecar','Long Island','Mudslide','Carriage')

"""Demikian pula, argumen juga dapat dimasukkan ke dalam dictionary seperti yang ditunjukkan pada contoh berikut ini:"""

def printDictionary(**args):
    for key in args:
        print(key + " : " + args[key])

printDictionary(Country='Canada',Province='Ontario',City='Toronto')

"""Fungsi bisa sangat berguna. Fungsi dapat menerima (dan mengembalikan) tipe data, objek, dan bahkan fungsi lain sebagai argumen. Perhatikan contoh di bawah ini:"""

def addItems(list):
    list.append("Three")
    list.append("Four")

myList = ["One","Two"]

addItems(myList)

myList

"""Perhatikan bagaimana perubahan yang dibuat pada list tidak terbatas pada lingkup fungsi. Hal ini terjadi karena list adalah sebuah objek **referensi** yang diteruskan ke fungsi.

Setiap perubahan akan diaplikasikan pada original list. Oleh karena itu, hati-hati saat mengirimkan objek yang bisa berubah (*mutable object*) ke dalam fungsi.

<hr>

<h2>Kuis tentang Fungsi</h2>

Buatlah fungsi yang membagi input pertama dengan input kedua:
"""

# Tulis kode Anda di bawah ini dan tekan Shift + Enter untuk mengeksekusi
def divide(num1, num2):
  result = num1 / num2
  return result

"""<hr>

Gunakan fungsi <code> con</code> untuk pertanyaan berikut.
"""

# Gunakan fungsi con untuk pertanyaan berikut.

def con(a, b):
    return(a + b)

con(3, 4)

"""Bisakah fungsi <code> con</code> yang kita definisikan sebelumnya digunakan untuk menambahkan dua bilangan bulat atau string?"""

# Beri contoh untuk menjawab pertanyaan di atas, lalu beri komentar sebagai kesimpulannya
con("three", "four") # Bisa
con(2, 4) # Bisa

"""<hr>

Bisakah fungsi <code> con </code> yang kita definisikan sebelumnya digunakan untuk menggabungkan (*concatenate*) lists atau tuples?
"""

# Tulis kode Anda di bawah ini dan tekan Shift + Enter untuk mengeksekusi
list1 = ["lion", "dog", 4]
list2 = ["shark", "dolphin", 69]
con(list1, list2) # Bisa

tuple1 = ("wolf", 4, "monkey")
tuple2 = (["bird", "fish"], 40, "sheep")
con(tuple1, tuple2) # Bisa

"""<hr>
<h2>Selamat!</h2>
<p>Anda telah menyelesaikan Modul Fungsi.
"""